title: The Canvas Blog
description: Blog about art, music, and design.
baseurl: "/newblog.github.io"  # Your repo name (with slash)
url: "https://thefuzz25.github.io"
markdown: kramdown
theme: minima
sass:
  sass_dir: assets/css
